// ─────────────────────────────────────────────────────────────
// Mock data for the logged-in experience. No API calls anywhere.
// Replace these with real fetches when the Fastify backend lands.
// ─────────────────────────────────────────────────────────────
import type {
  Applicant,
  Application,
  AppNotification,
  Posting,
  Reminder,
  SavedItem,
} from "./dashboard.types";

export const DEMO_STUDENT_ID = "stu_ayesha";
export const DEMO_ORG_ID = "org_daraz";

// ─── Student applications (mix of types, statuses, external/native) ──
export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "SCH-2026-000047",
    type: "scholarship",
    status: "shortlisted",
    isExternal: false,
    studentId: DEMO_STUDENT_ID,
    itemId: "sch_chevening",
    itemTitle: "Chevening Scholarship 2026",
    organizationName: "British Council",
    location: "United Kingdom",
    fundingAmount: "Fully funded",
    appliedAt: "2026-06-22T09:00:00Z",
    deadlineAt: "2026-11-07T23:59:00Z",
    lastStatusChangeAt: "2026-06-25T07:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-25T07:00:00Z",
        type: "status-change",
        description: "Status changed to Shortlisted",
        fromStatus: "under-review",
        toStatus: "shortlisted",
        actor: "organization",
      },
      {
        timestamp: "2026-06-24T11:30:00Z",
        type: "note",
        description: "Application reviewed by the selection committee",
        actor: "organization",
      },
      {
        timestamp: "2026-06-22T09:00:00Z",
        type: "submission",
        description: "Application submitted",
        actor: "student",
      },
    ],
  },
  {
    id: "INT-2026-000023",
    type: "internship",
    status: "under-review",
    isExternal: false,
    studentId: DEMO_STUDENT_ID,
    itemId: "int_daraz_swe",
    itemTitle: "Software Engineering Intern",
    organizationName: "Daraz Pakistan",
    location: "Karachi",
    fundingAmount: "PKR 45,000 / month",
    appliedAt: "2026-06-20T14:00:00Z",
    deadlineAt: "2026-09-30T23:59:00Z",
    lastStatusChangeAt: "2026-06-23T10:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-23T10:00:00Z",
        type: "status-change",
        description: "Status changed to Under Review",
        fromStatus: "submitted",
        toStatus: "under-review",
        actor: "organization",
      },
      {
        timestamp: "2026-06-20T14:00:00Z",
        type: "submission",
        description: "Application submitted",
        actor: "student",
      },
    ],
  },
  {
    id: "INT-2026-000031",
    type: "internship",
    status: "accepted",
    isExternal: false,
    studentId: DEMO_STUDENT_ID,
    itemId: "int_systems",
    itemTitle: "Frontend Developer Intern",
    organizationName: "Systems Limited",
    location: "Lahore",
    fundingAmount: "PKR 40,000 / month",
    appliedAt: "2026-05-30T08:00:00Z",
    deadlineAt: "2026-07-15T23:59:00Z",
    lastStatusChangeAt: "2026-06-18T12:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-18T12:00:00Z",
        type: "status-change",
        description: "Congratulations! Status changed to Accepted",
        fromStatus: "interview",
        toStatus: "accepted",
        actor: "organization",
      },
      {
        timestamp: "2026-06-12T15:00:00Z",
        type: "status-change",
        description: "Interview scheduled for 14 June",
        fromStatus: "shortlisted",
        toStatus: "interview",
        actor: "organization",
      },
      {
        timestamp: "2026-06-05T09:00:00Z",
        type: "submission",
        description: "Application submitted",
        actor: "student",
      },
    ],
  },
  {
    id: "SCH-2026-000052",
    type: "scholarship",
    status: "submitted",
    isExternal: false,
    studentId: DEMO_STUDENT_ID,
    itemId: "sch_hec_need",
    itemTitle: "HEC Need-Based Scholarship",
    organizationName: "Higher Education Commission",
    location: "Pakistan",
    fundingAmount: "Up to PKR 200,000 / year",
    appliedAt: "2026-06-24T16:00:00Z",
    deadlineAt: "2026-08-20T23:59:00Z",
    lastStatusChangeAt: "2026-06-24T16:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-24T16:00:00Z",
        type: "submission",
        description: "Application submitted",
        actor: "student",
      },
    ],
  },
  {
    id: "EXT-2026-000005",
    type: "scholarship",
    status: "external-applied",
    isExternal: true,
    studentId: DEMO_STUDENT_ID,
    itemId: "sch_fulbright",
    itemTitle: "Fulbright Foreign Student Program",
    organizationName: "USEFP",
    location: "United States",
    fundingAmount: "Fully funded",
    externalUrl: "https://www.usefp.org/",
    appliedAt: "2026-06-10T10:00:00Z",
    deadlineAt: "2026-05-15T23:59:00Z",
    lastStatusChangeAt: "2026-06-10T10:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-10T10:00:00Z",
        type: "note",
        description: "Marked as applied externally by you",
        actor: "student",
      },
    ],
  },
  {
    id: "INT-2026-000040",
    type: "internship",
    status: "not-selected",
    isExternal: false,
    studentId: DEMO_STUDENT_ID,
    itemId: "int_careem",
    itemTitle: "Product Design Intern",
    organizationName: "Careem",
    location: "Remote",
    fundingAmount: "PKR 50,000 / month",
    appliedAt: "2026-05-18T11:00:00Z",
    deadlineAt: "2026-06-10T23:59:00Z",
    lastStatusChangeAt: "2026-06-14T09:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-14T09:00:00Z",
        type: "status-change",
        description: "Status changed to Not Selected",
        fromStatus: "under-review",
        toStatus: "not-selected",
        actor: "organization",
      },
      {
        timestamp: "2026-05-18T11:00:00Z",
        type: "submission",
        description: "Application submitted",
        actor: "student",
      },
    ],
  },
  {
    id: "EXT-2026-000009",
    type: "internship",
    status: "external-applied",
    isExternal: true,
    studentId: DEMO_STUDENT_ID,
    itemId: "int_bykea",
    itemTitle: "Data Analyst Intern",
    organizationName: "Bykea",
    location: "Remote",
    externalUrl: "https://bykea.com/careers",
    appliedAt: "2026-06-15T13:00:00Z",
    lastStatusChangeAt: "2026-06-15T13:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-15T13:00:00Z",
        type: "note",
        description: "Marked as applied externally by you",
        actor: "student",
      },
    ],
  },
  {
    id: "SCH-2026-000061",
    type: "scholarship",
    status: "withdrawn",
    isExternal: false,
    studentId: DEMO_STUDENT_ID,
    itemId: "sch_aga_khan",
    itemTitle: "Aga Khan Foundation Scholarship",
    organizationName: "Aga Khan Foundation",
    location: "International",
    fundingAmount: "50% loan, 50% grant",
    appliedAt: "2026-05-25T10:00:00Z",
    deadlineAt: "2026-07-01T23:59:00Z",
    lastStatusChangeAt: "2026-06-08T10:00:00Z",
    timeline: [
      {
        timestamp: "2026-06-08T10:00:00Z",
        type: "status-change",
        description: "You withdrew this application",
        fromStatus: "submitted",
        toStatus: "withdrawn",
        actor: "student",
      },
      {
        timestamp: "2026-05-25T10:00:00Z",
        type: "submission",
        description: "Application submitted",
        actor: "student",
      },
    ],
  },
];

// ─── Org postings (Daraz) ────────────────────────────────────
export const MOCK_POSTINGS: Posting[] = [
  {
    id: "int_daraz_swe",
    type: "internship",
    status: "active",
    title: "Software Engineering Intern",
    description:
      "Join Daraz's engineering team to build features used by millions of shoppers across Pakistan. Work with React, Node.js and microservices.",
    organizationId: DEMO_ORG_ID,
    organizationName: "Daraz Pakistan",
    postedAt: "2026-06-21T09:00:00Z",
    deadlineAt: "2026-09-30T23:59:00Z",
    applyMethod: "platform",
    applicantCount: 12,
    newApplicantCount: 5,
    workMode: "onsite",
    city: "Karachi",
    isPaid: true,
    stipend: "PKR 45,000 / month",
    duration: "3 months",
    startDate: "2026-10-01",
  },
  {
    id: "int_daraz_marketing",
    type: "internship",
    status: "active",
    title: "Digital Marketing Intern",
    description:
      "Support campaign planning, social media and performance marketing for Daraz's biggest sale events.",
    organizationId: DEMO_ORG_ID,
    organizationName: "Daraz Pakistan",
    postedAt: "2026-06-12T09:00:00Z",
    deadlineAt: "2026-08-15T23:59:00Z",
    applyMethod: "platform",
    applicantCount: 28,
    newApplicantCount: 7,
    workMode: "hybrid",
    city: "Lahore",
    isPaid: true,
    stipend: "PKR 35,000 / month",
    duration: "6 months",
    startDate: "2026-09-01",
  },
  {
    id: "int_daraz_finance",
    type: "internship",
    status: "active",
    title: "Finance & Operations Intern",
    description:
      "Assist the finance team with reporting, reconciliation and operational analytics.",
    organizationId: DEMO_ORG_ID,
    organizationName: "Daraz Pakistan",
    postedAt: "2026-06-01T09:00:00Z",
    deadlineAt: "2026-07-31T23:59:00Z",
    applyMethod: "external",
    externalUrl: "https://careers.daraz.pk/finance-intern",
    applicantCount: 41,
    newApplicantCount: 3,
    workMode: "onsite",
    city: "Karachi",
    isPaid: true,
    stipend: "PKR 40,000 / month",
    duration: "3 months",
    startDate: "2026-08-15",
  },
  {
    id: "int_daraz_ux",
    type: "internship",
    status: "draft",
    title: "UX Research Intern",
    description:
      "Help the design team run usability studies and synthesise insights. (Draft- not yet published.)",
    organizationId: DEMO_ORG_ID,
    organizationName: "Daraz Pakistan",
    postedAt: "2026-06-24T09:00:00Z",
    applyMethod: "platform",
    applicantCount: 0,
    newApplicantCount: 0,
    workMode: "remote",
    isPaid: true,
    stipend: "PKR 38,000 / month",
    duration: "3 months",
  },
  {
    id: "int_daraz_cs",
    type: "internship",
    status: "closed",
    title: "Customer Success Intern",
    description:
      "Worked with the CS team to improve buyer satisfaction. This posting is now closed.",
    organizationId: DEMO_ORG_ID,
    organizationName: "Daraz Pakistan",
    postedAt: "2026-03-10T09:00:00Z",
    deadlineAt: "2026-04-30T23:59:00Z",
    applyMethod: "platform",
    applicantCount: 61,
    newApplicantCount: 0,
    workMode: "onsite",
    city: "Karachi",
    isPaid: true,
    stipend: "PKR 30,000 / month",
    duration: "2 months",
  },
];

// ─── Applicants across postings ──────────────────────────────
const FIELDS = [
  "Computer Science",
  "Software Engineering",
  "Business Administration",
  "Electrical Engineering",
  "Data Science",
  "Graphic Design",
];
const UNIS = ["NUST", "LUMS", "FAST-NUCES", "GIKI", "IBA Karachi", "COMSATS", "UET Lahore"];
const NAMES: [string, string][] = [
  ["Ayesha Khan", "AK"],
  ["Hassan Raza", "HR"],
  ["Fatima Noor", "FN"],
  ["Bilal Ahmed", "BA"],
  ["Zara Sheikh", "ZS"],
  ["Usman Tariq", "UT"],
  ["Maryam Javed", "MJ"],
  ["Ali Hamza", "AH"],
  ["Sana Malik", "SM"],
  ["Hamza Iqbal", "HI"],
  ["Iqra Aslam", "IA"],
  ["Saad Qureshi", "SQ"],
  ["Noor Fatima", "NF"],
  ["Talha Yousuf", "TY"],
  ["Rabia Hassan", "RH"],
  ["Daniyal Khan", "DK"],
  ["Aiman Riaz", "AR"],
  ["Faizan Ali", "FA"],
  ["Hira Shah", "HS"],
  ["Owais Mir", "OM"],
  ["Komal Nadeem", "KN"],
  ["Shayan Butt", "SB"],
  ["Eman Zafar", "EZ"],
  ["Arsalan Dar", "AD"],
];
const APPLICANT_STATUSES = [
  "submitted",
  "submitted",
  "under-review",
  "under-review",
  "shortlisted",
  "interview",
  "accepted",
  "not-selected",
] as const;

export const MOCK_APPLICANTS: Applicant[] = NAMES.map(([name, initials], i) => {
  const posting = MOCK_POSTINGS[i % 3]; // spread across the 3 active postings
  const day = 25 - (i % 12); // applied within the last ~12 days
  return {
    id: `app_${i + 1}`,
    applicationId: `INT-2026-${String(100 + i).padStart(6, "0")}`,
    postingId: posting.id,
    postingTitle: posting.title,
    name,
    initials,
    email: `${name.toLowerCase().replace(/\s+/g, ".")}@${UNIS[i % UNIS.length]
      .toLowerCase()
      .replace(/[^a-z]/g, "")}.edu.pk`,
    university: UNIS[i % UNIS.length],
    degreeLevel: "Undergraduate",
    fieldOfStudy: FIELDS[i % FIELDS.length],
    gpa: (3.2 + ((i * 7) % 8) / 10).toFixed(1),
    city: ["Karachi", "Lahore", "Islamabad", "Faisalabad"][i % 4],
    skills: ["React", "Node.js", "Figma", "SQL", "Python"].slice(0, (i % 4) + 1),
    appliedAt: `2026-06-${String(day).padStart(2, "0")}T10:00:00Z`,
    status: APPLICANT_STATUSES[i % APPLICANT_STATUSES.length],
    coverLetter:
      "I'm passionate about building products that reach Pakistani users at scale, and I believe this internship is the perfect place to grow.",
  };
});

// ─── Notifications ───────────────────────────────────────────
export const MOCK_NOTIFICATIONS_STUDENT: AppNotification[] = [
  {
    id: "n1",
    userId: DEMO_STUDENT_ID,
    type: "application-status",
    title: "Your application was shortlisted 🎉",
    subtitle: "Chevening Scholarship 2026 · British Council · 2 hours ago",
    link: "/dashboard/applications/SCH-2026-000047",
    read: false,
    createdAt: "2026-06-25T07:00:00Z",
  },
  {
    id: "n2",
    userId: DEMO_STUDENT_ID,
    type: "application-status",
    title: "Application moved to Under Review",
    subtitle: "Software Engineering Intern · Daraz · 2 days ago",
    link: "/dashboard/applications/INT-2026-000023",
    read: false,
    createdAt: "2026-06-23T10:00:00Z",
  },
  {
    id: "n3",
    userId: DEMO_STUDENT_ID,
    type: "deadline-reminder",
    title: "Deadline approaching",
    subtitle: "Aga Khan Foundation Scholarship closes in 6 days",
    link: "/dashboard/reminders",
    read: false,
    createdAt: "2026-06-25T06:00:00Z",
  },
  {
    id: "n4",
    userId: DEMO_STUDENT_ID,
    type: "application-status",
    title: "You got an offer! 🎓",
    subtitle: "Frontend Developer Intern · Systems Limited · 1 week ago",
    link: "/dashboard/applications/INT-2026-000031",
    read: true,
    createdAt: "2026-06-18T12:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS_ORG: AppNotification[] = [
  {
    id: "on1",
    userId: DEMO_ORG_ID,
    type: "new-applicant",
    title: "5 new applicants",
    subtitle: "Software Engineering Intern · today",
    link: "/org/postings/int_daraz_swe",
    read: false,
    createdAt: "2026-06-25T08:00:00Z",
  },
  {
    id: "on2",
    userId: DEMO_ORG_ID,
    type: "new-applicant",
    title: "New applicant: Ayesha Khan",
    subtitle: "Software Engineering Intern · 3 hours ago",
    link: "/org/applicants/app_1",
    read: false,
    createdAt: "2026-06-25T05:00:00Z",
  },
  {
    id: "on3",
    userId: DEMO_ORG_ID,
    type: "system",
    title: "Your organization is verified ✓",
    subtitle: "You can now publish public postings · yesterday",
    read: true,
    createdAt: "2026-06-24T09:00:00Z",
  },
];

// ─── Saved items ─────────────────────────────────────────────
export const MOCK_SAVED_ITEMS: SavedItem[] = [
  {
    id: "sch_chevening",
    type: "scholarship",
    title: "Chevening Scholarship 2026",
    organizationName: "British Council",
    location: "United Kingdom",
    fundingAmount: "Fully funded",
    deadlineAt: "2026-11-07T23:59:00Z",
    reminderSet: true,
  },
  {
    id: "sch_aga_khan",
    type: "scholarship",
    title: "Aga Khan Foundation Scholarship",
    organizationName: "Aga Khan Foundation",
    location: "International",
    fundingAmount: "50% loan, 50% grant",
    deadlineAt: "2026-07-01T23:59:00Z",
    reminderSet: true,
  },
  {
    id: "int_careem",
    type: "internship",
    title: "Backend Engineer Intern",
    organizationName: "Careem",
    location: "Remote",
    stipend: "PKR 50,000 / month",
    deadlineAt: "2026-06-28T23:59:00Z",
  },
  {
    id: "int_foodpanda",
    type: "internship",
    title: "Growth Marketing Intern",
    organizationName: "foodpanda",
    location: "Lahore",
    stipend: "PKR 30,000 / month",
    deadlineAt: "2026-07-20T23:59:00Z",
  },
  {
    id: "sch_hec_indigenous",
    type: "scholarship",
    title: "HEC Indigenous PhD Fellowship",
    organizationName: "Higher Education Commission",
    location: "Pakistan",
    fundingAmount: "Monthly stipend + tuition",
    deadlineAt: "2026-09-10T23:59:00Z",
  },
  {
    id: "int_bazaar",
    type: "internship",
    title: "Software Intern",
    organizationName: "Bazaar Technologies",
    location: "Karachi",
    stipend: "PKR 42,000 / month",
    deadlineAt: "2026-08-05T23:59:00Z",
  },
];

// ─── Reminders ───────────────────────────────────────────────
export const MOCK_REMINDERS: Reminder[] = [
  {
    id: "r1",
    itemTitle: "Chevening Scholarship 2026",
    remindAt: "2026-10-31T09:00:00Z",
    daysBefore: 7,
    channel: "email",
  },
  {
    id: "r2",
    itemTitle: "Aga Khan Foundation Scholarship",
    remindAt: "2026-06-28T09:00:00Z",
    daysBefore: 3,
    channel: "both",
  },
];
