import type { Internship } from "./internships.types";

export const MOCK_INTERNSHIPS: Internship[] = [
  {
    id: "int-001",
    title: "Software Engineering Intern",
    company: "Daraz",
    companyInitials: "D",
    workMode: "onsite",
    workType: "internship",
    field: "software-it",
    city: "Karachi",
    isPaid: true,
    stipend: "PKR 45,000/month",
    duration: "6 months",
    startDate: "July 2026",
    applyUrl: "https://careers.daraz.com",
    deadline: "2026-07-10",
    summary:
      "Work alongside Daraz's core platform team building and shipping features for Pakistan's largest e-commerce marketplace.",
    postedAt: "2026-06-21",
  },
  {
    id: "int-002",
    title: "Frontend Developer Intern",
    company: "Bykea",
    companyInitials: "B",
    workMode: "remote",
    workType: "internship",
    field: "software-it",
    city: null,
    isPaid: true,
    stipend: "PKR 35,000/month",
    duration: "3 months",
    startDate: "August 2026",
    applyUrl: "https://bykea.com/careers",
    deadline: "2026-07-05",
    summary:
      "Build delightful rider and customer-facing interfaces in React for Pakistan's leading ride-hailing and logistics app.",
    postedAt: "2026-06-20",
  },
  {
    id: "int-003",
    title: "Digital Marketing Intern",
    company: "Foodpanda",
    companyInitials: "F",
    workMode: "hybrid",
    workType: "internship",
    field: "marketing",
    city: "Lahore",
    isPaid: true,
    stipend: "PKR 30,000/month",
    duration: "3 months",
    startDate: "July 2026",
    applyUrl: "https://www.foodpanda.pk/careers",
    deadline: "2026-06-28",
    summary:
      "Plan and run social campaigns, analyze funnel performance, and support growth experiments across major Pakistani cities.",
    postedAt: "2026-06-18",
  },
  {
    id: "int-004",
    title: "UI/UX Design Intern",
    company: "Careem",
    companyInitials: "C",
    workMode: "remote",
    workType: "internship",
    field: "design",
    city: null,
    isPaid: true,
    stipend: "PKR 50,000/month",
    duration: "6 months",
    startDate: "Rolling",
    applyUrl: "https://careem.com/careers",
    deadline: null,
    summary:
      "Design intuitive flows for the Careem super-app, from wireframes to polished prototypes, with mentorship from senior designers.",
    postedAt: "2026-06-15",
  },
  {
    id: "int-005",
    title: "Finance & Accounts Intern",
    company: "Systems Limited",
    companyInitials: "SL",
    workMode: "onsite",
    workType: "internship",
    field: "finance",
    city: "Lahore",
    isPaid: true,
    stipend: "PKR 28,000/month",
    duration: "3 months",
    startDate: "July 2026",
    applyUrl: "https://systemsltd.com/careers",
    deadline: "2026-07-15",
    summary:
      "Assist the finance team with reconciliations, reporting, and month-end close at one of Pakistan's largest IT companies.",
    postedAt: "2026-06-14",
  },
  {
    id: "int-006",
    title: "Backend Engineering Intern",
    company: "NETSOL Technologies",
    companyInitials: "N",
    workMode: "onsite",
    workType: "internship",
    field: "software-it",
    city: "Lahore",
    isPaid: true,
    stipend: "PKR 40,000/month",
    duration: "6 months",
    startDate: "August 2026",
    applyUrl: "https://netsoltech.com/careers",
    deadline: "2026-07-20",
    summary:
      "Develop and test APIs for enterprise leasing and finance software used by global automotive clients.",
    postedAt: "2026-06-12",
  },
  {
    id: "int-007",
    title: "Content Writing Intern",
    company: "Markhor Creative",
    companyInitials: "MC",
    workMode: "remote",
    workType: "part-time",
    field: "marketing",
    city: null,
    isPaid: false,
    stipend: null,
    duration: "2 months",
    startDate: "Rolling",
    applyUrl: "https://example.com/markhor-careers",
    deadline: "2026-06-26",
    summary:
      "Write blogs, ad copy, and social posts for local and international brands at a boutique Lahore creative agency.",
    postedAt: "2026-06-11",
  },
  {
    id: "int-008",
    title: "Data Analyst Intern",
    company: "Sastaticket.pk",
    companyInitials: "S",
    workMode: "hybrid",
    workType: "internship",
    field: "software-it",
    city: "Islamabad",
    isPaid: true,
    stipend: "PKR 32,000/month",
    duration: "4 months",
    startDate: "July 2026",
    applyUrl: "https://sastaticket.pk/careers",
    deadline: "2026-08-01",
    summary:
      "Turn booking and pricing data into dashboards and insights that drive product and revenue decisions.",
    postedAt: "2026-06-10",
  },
  {
    id: "int-009",
    title: "Sales & Business Development Intern",
    company: "Bazaar Technologies",
    companyInitials: "BT",
    workMode: "onsite",
    workType: "internship",
    field: "sales",
    city: "Karachi",
    isPaid: true,
    stipend: "PKR 25,000/month",
    duration: "3 months",
    startDate: "July 2026",
    applyUrl: "https://bazaartech.com/careers",
    deadline: "2026-07-08",
    summary:
      "Support the B2B sales team onboarding retailers onto Pakistan's fast-growing wholesale commerce platform.",
    postedAt: "2026-06-09",
  },
  {
    id: "int-010",
    title: "Graphic Design Intern",
    company: "Walee Technologies",
    companyInitials: "W",
    workMode: "remote",
    workType: "part-time",
    field: "design",
    city: null,
    isPaid: true,
    stipend: "PKR 22,000/month",
    duration: "3 months",
    startDate: "Rolling",
    applyUrl: "https://walee.pk/careers",
    deadline: null,
    summary:
      "Create social-first visuals and motion assets for influencer marketing campaigns across the region.",
    postedAt: "2026-06-07",
  },
  {
    id: "int-011",
    title: "Mechanical Engineering Intern",
    company: "Millat Tractors",
    companyInitials: "MT",
    workMode: "onsite",
    workType: "internship",
    field: "engineering",
    city: "Lahore",
    isPaid: true,
    stipend: "PKR 26,000/month",
    duration: "6 months",
    startDate: "August 2026",
    applyUrl: "https://millat.com.pk/careers",
    deadline: "2026-07-25",
    summary:
      "Hands-on rotation across production, quality, and maintenance at Pakistan's leading tractor manufacturer.",
    postedAt: "2026-06-05",
  },
  {
    id: "int-012",
    title: "Mobile App Developer Intern",
    company: "Airlift Express",
    companyInitials: "A",
    workMode: "hybrid",
    workType: "internship",
    field: "software-it",
    city: "Islamabad",
    isPaid: true,
    stipend: "PKR 38,000/month",
    duration: "4 months",
    startDate: "July 2026",
    applyUrl: "https://example.com/airlift-careers",
    deadline: "2026-08-10",
    summary:
      "Ship features for a high-traffic Flutter app, working closely with product and backend teams.",
    postedAt: "2026-06-03",
  },
  {
    id: "int-013",
    title: "HR & Operations Intern",
    company: "Tech Avenue",
    companyInitials: "TA",
    workMode: "onsite",
    workType: "full-time",
    field: "other",
    city: "Karachi",
    isPaid: false,
    stipend: null,
    duration: "2 months",
    startDate: "July 2026",
    applyUrl: "https://example.com/techavenue-careers",
    deadline: "2026-06-30",
    summary:
      "Support recruitment, onboarding, and day-to-day operations at a growing software house.",
    postedAt: "2026-06-01",
  },
  {
    id: "int-014",
    title: "Finance Analyst Intern",
    company: "Abhi Finance",
    companyInitials: "AF",
    workMode: "remote",
    workType: "internship",
    field: "finance",
    city: null,
    isPaid: true,
    stipend: "PKR 42,000/month",
    duration: "6 months",
    startDate: "Rolling",
    applyUrl: "https://abhi.com.pk/careers",
    deadline: null,
    summary:
      "Build financial models and analyses for a leading Pakistani fintech reshaping access to earned-wage advances.",
    postedAt: "2026-05-28",
  },
];
